[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
  '@solmate=lib/solmate/src',
  '@openzeppelin=node_modules/@openzeppelin'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
